name: build-pr

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8','11','17', '21']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: maven
      - name: Maven -v
        run: mvn -v
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=${{ github.sha }}


  release-dev:
    name: Create release - dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Upload artifact
        run: mvn -B deploy -Dgithub-release -e -Drevision=dev-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}